name: Create AI assessment
description: Generate an AI assessment for a given domain.

body:
  - type: input
    id: game_name
    attributes:
      description: Game to perform assessment on
      placeholder: "Arc Raiders"
    validations:
      required: true
